settings:
  application:
    env: dev
    envmsg: "谢谢您的参与，但为了大家更好的体验，所以本次提交就算了吧！\U0001F600\U0001F600\U0001F600"
    host: 0.0.0.0
    isinit: false
    logpath: temp/logs/log.txt
    name: testApp
    port: 8000
    readtimeout: 1
    writertimeout: 2
  jwt:
    secret: leonote
    timeout: 3600
#  db:
#    host: 127.0.0.1
#    database: leonote
#    dbtype: mysql
#    #    password: 123456
#    port: 3306
#    username: root

#  database:
#    dbtype: mysql  #sqlite3
#    write:
#      host: 127.0.0.1  #sqlite3.db
#      dbname: leonote
#      port: 3306
#      username: root
#      password: 123456
#    read:
#      - host: 127.0.0.1
#        dbname: leonote
#        port: 3306
#        username: root
#        password: 123456
#      - host: 127.0.0.1
#        dbname: leonote
#        port: 3306
#        username: root
#        password: 123456
#      - host: 127.0.0.1
#        dbname: leonote
#        port: 3306
#        username: root
#        password: 123456
  database:
    dbType: mysql
    prefix: leo_
    uri:
      - root:@/leonote?charset=utf8;   #master
      - root:@/leonote?charset=utf8;
      - root:@/leonote?charset=utf8;
      - root:@/leonote?charset=utf8;

  page:
    pageSize: 20

