settings:

  application:
    env: dev
    domain: 127.0.0.1
    envmsg: "谢谢您的参与，但为了大家更好的体验，所以本次提交就算了吧！\U0001F600\U0001F600\U0001F600"
    host: 0.0.0.0
    isinit: false
    logpath: temp/logs/log.txt
    name: testApp
    port: 8000
    readtimeout: 1
    writertimeout: 2

  jwt:
    key: "leonote jwt"
    timeout: 3600
    tokenLookup: "header: Authorization, query: token, cookie: jwt"
    tokenHeadName: "Bearer"
    SigningAlgorithm: HS256
    secret: leonote
    cookie: jwt

  database:
    dbType: mysql
    prefix: leo_
    uri:
      - root:@/leonote?charset=utf8;   #master
      - root:@/leonote?charset=utf8;   #slave
      - root:@/leonote?charset=utf8;   #slave
      - root:@/leonote?charset=utf8;   #slave

  page:
    pageSize: 20

